#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1207572141                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.booleanbites.imagitor                                          # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Imagitor                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Text on photos                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Imagitor is a free app to add text to your photos.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Adil Soomro                                
your_link                                 : http://booleanbites.com                     
your_city                                 : Lahore, Pakistan                                
email_address                             : booleanbites@gmail.com
facebook_username                         : imagitor                                          
instagram_username                        : imagitor
twitter_username                          : imagitor
youtube_username                          : imagitor



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Large Collection of Urdu Fonts
    description                           : Have access to our collection of stylish Urdu fonts.
    fontawesome_icon_name                 : font
    
  - title                                 : Beautify your text with many Text Effects
    description                           : Make your text stand out with dozens of text effects like Gradients, Shadow, Stroke, Background
    fontawesome_icon_name                 : magic
    
  - title                                 : Sayt it with expressive Stickers and Shapes
    description                           : Add stickers, emojis, shapes, as you want
    fontawesome_icon_name                 : star
    
  - title                                 : Create your social media Logo
    description                           : With stickers, shapes and text, create your own professional logo
    fontawesome_icon_name                 : shapes

  - title                                 : Save your works as Project
    description                           : Create a master piece and save it as project for future editions.
    fontawesome_icon_name                 : save
    
  - title                                 : Embellish and Enhance
    description                           : Urdu Editor comes with easy-to-use editing tools to help you make the text look amazing
    fontawesome_icon_name                 : microscope

  - title                                 : Format Urdu Like a Pro!
    description                           : Experiment with many fonts, dozen colors, size and border to create artful effects for your Urdu text.
    fontawesome_icon_name                 : dragon

  - title                                 : Resize Canvas, Background Color
    description                           : Quickly focus on what’s important and personalize with background color and resize your canvas to best fit your crafty requirements.
    fontawesome_icon_name                 : sync

  - title                                 : Share from App
    description                           : Save your editing to your camera roll, or share with your social directly from the app by posting to facebook and twitter.
    fontawesome_icon_name                 : share

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
